'use strict';

angular.module('dynoforceApp')
.factory('nameGen', function() {
	return {
		firstname: [
		'Titan', 'Sequoia', 'Stampede', 'Fermi', 'Nebula',
		'Pleiades', 'Helios', 'Cielo', 'Hopper', 'Yellowstone', 'Roadrunner', 'Cherno',
		'Zin', 'Raptor', 'Avoca', 'Sakura', 'Himawari', 'Intrepid', 'Ranger', 'Discover',
		'Dawn', 'Endeavor', 'Pershing', 'Luna', 'Vulcan', 'Spirit', 'Pecos', 'Chama',
		'Kilrain', 'Zeus', 'Garnet', 'Blackthorn', 'Hercules', 'Triolith', 'Tachyonll',
		'Amazon', 'Moonlight', 'Jade', 'Zeus', 'Mustang', 'Ruby', 'Gyre', 'Tide', 'Vesta',
		'Sierra', 'Willow', 'Laurel', 'Cluster', 'Encanto', 'Juno', 'Jet', 'Hera', 'Emerald',
		'Aurora', 'Beacon', 'Hybrid', 'Lattice', 'Copper', 'Olympus', 'Edge', 'Palmetto',
		'Boomer', 'Fission', 'Typhoon', 'Nimbus', 'Midway', 'Mana', 'Oakley', 'Brawler',
		'Yukon', 'Coyote', 'Alpha', 'Tango', 'Horizon', 'Brave', 'Romeo', 'Blue', 'Tacit',
		'Ronin', 'Diablo', 'Intercept', 'Solar', 'Prophet', 'Puma', 'Real', 'Eden', 'Assassin',
		'Gipsy', 'Danger', 'Matador', 'Fury', 'Shaolin', 'Rogue', 'Specter', 'Chrome', 'Brutus',
		'Crimson', 'Striker', 'Eureka', 'Nova', 'Hyperion', 'Echo', 'Saber', 'Mammoth', 'Apostle',
		'Hydra', 'Corinthian', 'Lucky', 'Yankee', 'Renegade', 'Bombshell', 'Swift', 'Raging',
		'Bravo', 'Foxtrot', 'Tango', 'Victor', 'Whisky', 'Zulu', 'Atlas', 'Avenger', 'Banshee',
		'Boomerang', 'Brigand', 'Buccaneer', 'Buffalo', 'Comet', 'Coronado', 'Corsair', 'Defiant',
		'Devastator', 'Dominator', 'Dragon', 'Eagle', 'Electra', 'Envoy', 'Express', 'Falcon',
		'Fireball', 'Firebrand', 'Firefly', 'Fox', 'Gauntlet', 'Gladiator', 'Grizzly', 'Havoc',
		'Hawk', 'Helldiver', 'Hotspur', 'Hurricane', 'Invader', 'Lancer', 'Liberator', 'Lightning',
		'MAriner', 'Mars', 'Master', 'Mentor', 'Meteor', 'Nomad', 'Orion', 'Phantom', 'Proctor',
		'Rapid', 'Reliant', 'Scimitar', 'Sentinel', 'Shrike', 'Spitfire', 'Stirling', 'Tempest',
		'Thunderbolt', 'Tornado', 'Valiant', 'Vanguard', 'Vega', 'Vengeance', 'Vindicator',
		'Voyager', 'Whirlwind', 'Wildcat', 'Zero', 'Brawler', 'Coyote', 'Horizon', 'Romeo', 'Juliet',
		'Tacit', 'Cherno', 'Tango', 'Diablo', 'Solar', 'Puma', 'Eden', 'Gipsy', 'Matador',
		'Shaolin', 'Vulcan', 'Chrome', 'Crimson', 'Hydra', 'Nova', 'Echo', 'Mammoth', 'Striker', 'Lucky'
		],

		lastname: [
		'Titan', 'Sequoia', 'Mira', 'Stampede', 'Fermi', 'Nebula',
		'Pleiades', 'Helios', 'Cielo', 'Hopper', 'Yellowstone', 'Roadrunner', 'Cherno',
		'Zin', 'Raptor', 'Avoca', 'Sakura', 'Himawari', 'Intrepid', 'Ranger', 'Discover',
		'Dawn', 'Endeavor', 'Pershing', 'Luna', 'Vulcan', 'Spirit', 'Pecos', 'Chama',
		'Kilrain', 'Zeus', 'Garnet', 'Blackthorn', 'Hercules', 'Triolith', 'Tachyonll',
		'Amazon', 'Moonlight', 'Jade', 'Zeus', 'Mustang', 'Ruby', 'Gyre', 'Tide', 'Vesta',
		'Sierra', 'Willow', 'Laurel', 'Cluster', 'Encanto', 'Juno', 'Jet', 'Hera', 'Emerald',
		'Aurora', 'Beacon', 'Hybrid', 'Lattice', 'Copper', 'Olympus', 'Edge', 'Palmetto',
		'Boomer', 'Fission', 'Typhoon', 'Nimbus', 'Midway', 'Mana', 'Oakley', 'Brawler',
		'Yukon', 'Coyote', 'Alpha', 'Tango', 'Horizon', 'Brave', 'Romeo', 'Blue',
		'Ronin', 'Diablo', 'Intercept', 'Solar', 'Prophet', 'Puma', 'Real', 'Eden', 'Assassin',
		'Gipsy', 'Danger', 'Matador', 'Fury', 'Shaolin', 'Rogue', 'Specter', 'Chrome', 'Brutus',
		'Crimson', 'Striker', 'Eureka', 'Nova', 'Hyperion', 'Echo', 'Saber', 'Mammoth', 'Apostle',
		'Hydra', 'Corinthian', 'Lucky', 'Yankee', 'Beta', 'Omega', 'Gamma', 'Delta', 'Epsilon',
		'Theta', 'Omicron', 'Pi',
		'Sigma', 'Renegade', 'Bombshell', 'Swift', 'Raging',
		'Bravo', 'Foxtrot', 'Tango', 'Victor', 'Whisky', 'Zulu', 'Atlas', 'Avenger', 'Banshee',
		'Boomerang', 'Brigand', 'Buccaneer', 'Buffalo', 'Comet', 'Coronado', 'Corsair', 'Defiant',
		'Devastator', 'Dominator', 'Dragon', 'Eagle', 'Electra', 'Envoy', 'Express', 'Falcon',
		'Fireball', 'Firebrand', 'Firefly', 'Fox', 'Gauntlet', 'Gladiator', 'Grizzly', 'Havoc',
		'Hawk', 'Helldiver', 'Hotspur', 'Hurricane', 'Invader', 'Lancer', 'Liberator', 'Lightning',
		'Mariner', 'Mars', 'Master', 'Mentor', 'Meteor', 'Nomad', 'Orion', 'Phantom',
		'Rapid', 'Reliant', 'Scimitar', 'Sentinel', 'Shrike', 'Spitfire', 'Stirling', 'Tempest',
		'Thunderbolt', 'Tornado', 'Valiant', 'Vanguard', 'Vega', 'Vengeance', 'Vindicator',
		'Voyager', 'Whirlwind', 'Wildcat', 'Zero', 'Yukon', 'Tango', 'Brave', 'Blue', 'Ronin', 'Alpha',
		'Tasmania', 'Intercept', 'Prophet', 'Real', 'Assassin', 'Danger', 'Fury', 'Rogue',
		'Specter', 'Brutus', 'Typhoon', 'Corinthian', 'Hyperion', 'Saber', 'Apostle', 'Eureka', 'Seven'
		],
		getMechName: function() {
			var first = this.firstname[Math.floor(Math.random()*this.firstname.length)];
			var last = first;
			while (last === first) {
				last = this.lastname[Math.floor(Math.random()*this.lastname.length)];
			}
			return first + ' ' + last;
		},
		getPilotName: function() {
			return this.pilots[Math.floor(Math.random()*this.pilots.length)];
		},
		pilots: [
		'Lightning',
		'Enzo',
		'Savernake',
		'Koko',
		'Hershey',
		'Cholo',
		'Elvis',
		'Machen',
		'Adonis',
		'Savernake',
		'Beefeater',
		'Sauce',
		'Bolero',
		'Titian',
		'Morocco',
		'Smores',
		'Caboodle',
		'Taro',
		'Chief',
		'Grunge',
		'Sweetheart',
		'Rover',
		'Sneezy',
		'Sweeney',
		'Squid',
		'Santini',
		'Solo',
		'Moochy',
		'Fido',
		'Nickleby',
		'Cromwell',
		'Oink',
		'Fizz',
		'Pupa',
		'Chiquita',
		'Haley',
		'Knaidel',
		'Sugar',
		'Boone',
		'Ares',
		'Queeny',
		'Amy',
		'Inca',
		'Napa',
		'Geezer',
		'Periwinkle',
		'Hog',
		'Patsy',
		'Mee-Krob',
		'Flora',
		'Mulan',
		'Napa',
		'Hobbit',
		'Wilhelmina',
		'Peppermint',
		'Cuddles',
		'Nelly',
		'Panama',
		'Remington',
		'Drambuie',
		'Zippi',
		'Dudette',
		'Bologna',
		'Calico',
		'Boz',
		'Wink',
		'Goomba',
		'Cypress',
		'Pokerface',
		'MoJo',
		'Snoopy',
		'Mariachi',
		'Rhodes',
		'Lunatic',
		'Saber',
		'Mutant',
		'Hershey',
		'Pickles',
		'Football',
		'Babbit',
		'Bumba',
		'Baby',
		'Zephyr',
		'Gator',
		'Munchkin',
		'Dusty',
		'Cheetah',
		'Cognac',
		'Andalusia',
		'Stellar',
		'Rotten',
		'Howler',
		'Bones',
		'Mutt',
		'Pachyderm',
		'Satin',
		'Prodigy',
		'Count',
		'Trouble',
		'Vanilla',
		'Angstrom',
		'Ira',
		'Sugarplum',
		'Daisy',
		'Harpo',
		'Holly',
		'Buffy',
		'Joppa',
		'Salamander',
		'Sashimi',
		'Gulliver',
		'Cha-Cha',
		'Mozart',
		'Bonsai',
		'Bullion',
		'Ragmop',
		'Sorbet',
		'Lady',
		'Maduro',
		'Fletch',
		'Gorilla',
		'Crusader',
		'Jai Alai',
		'Kelly',
		'Yukon',
		'Viva',
		'Pugnose',
		]
	};
});
